- name: Ensure required packages are installed
  apt:
    name:
      - curl
      - tar
    state: present
    update_cache: yes

- name: Create install directory
  file:
    path: "{{ beszel_install_dir }}"
    state: directory
    owner: "{{ beszel_user }}"
    group: "{{ beszel_user }}"
    mode: '0755'

- name: Download Beszel agent .deb
  get_url:
    url: "{{ beszel_deb_url }}"
    dest: "{{ beszel_deb_local_path }}"

- name: Install Beszel agent
  apt:
    deb: "{{ beszel_deb_local_path }}"
    state: present

- name: Create systemd service file for Beszel
  copy:
    dest: /etc/systemd/system/beszel.service
    content: |
      [Unit]
      Description=Beszel Hub
      After=network.target

      [Service]
      Type=simple
      Restart=always
      RestartSec=3
      User={{ beszel_user }}
      WorkingDirectory={{ beszel_install_dir }}
      ExecStart={{ beszel_install_dir }}/beszel serve --http "0.0.0.0:{{ beszel_http_port }}"

      [Install]
      WantedBy=multi-user.target
  notify: Restart Beszel

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start beszel service
  systemd:
    name: beszel
    enabled: yes
    state: started
